//
// OrganizationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class OrganizationAPI: APIBase {
    /**
     Get organization.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOrganizationsMe(completion: ((data: ININOrganization?, error: ErrorType?) -> Void)) {
        getOrganizationsMeWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get organization.
     - GET /api/v2/organizations/me
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example={
  "thirdPartyOrgName" : "aeiou",
  "defaultSiteId" : "aeiou",
  "domain" : "aeiou",
  "selfUri" : "aeiou",
  "name" : "aeiou",
  "thirdPartyOrgId" : "aeiou",
  "thirdPartyURI" : "aeiou",
  "deletable" : true,
  "id" : "aeiou",
  "state" : "aeiou",
  "version" : 123
}}]

     - returns: RequestBuilder<ININOrganization> 
     */
    public class func getOrganizationsMeWithRequestBuilder() -> RequestBuilder<ININOrganization> {
        let path = "/api/v2/organizations/me"
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ININOrganization>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
