//
// ININFacetResultItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININFacetResultItem: JSONEncodable {
    /** For TERM facets this will contain the value of the term that was found userid, docid, etc. */
    public var name: String?
    /** The number of items that matched the facetRequest. */
    public var count: Int64?
    public var document: ININDocument?
    public var user: ININUser?
    public var queue: ININQueue?
    public var flowConfigId: ININFlowConfigId?
    public var workspace: ININWorkspace?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["document"] = self.document?.encodeToJSON()
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["queue"] = self.queue?.encodeToJSON()
        nillableDictionary["flowConfigId"] = self.flowConfigId?.encodeToJSON()
        nillableDictionary["workspace"] = self.workspace?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
