//
// ININMediaPolicies.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININMediaPolicies: JSONEncodable {
    /** Conditions and actions for calls */
    public var callPolicy: ININCallMediaPolicy?
    /** Conditions and actions for chats */
    public var chatPolicy: ININChatMediaPolicy?
    /** Conditions and actions for emails */
    public var emailPolicy: ININEmailMediaPolicy?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["callPolicy"] = self.callPolicy?.encodeToJSON()
        nillableDictionary["chatPolicy"] = self.chatPolicy?.encodeToJSON()
        nillableDictionary["emailPolicy"] = self.emailPolicy?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
