//
// ININGroupMembersUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININGroupMembersUpdate: JSONEncodable {
    public var memberIds: [String]?
    public var version: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["memberIds"] = self.memberIds?.encodeToJSON()
        nillableDictionary["version"] = self.version?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
