//
// ININSystemPromptAsset.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININSystemPromptAsset: JSONEncodable {
    public enum ININUploadStatus: String { 
        case Created = "CREATED"
        case Uploaded = "UPLOADED"
        case Transcoded = "TRANSCODED"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var promptId: String?
    public var language: String?
    public var durationSeconds: Double?
    public var mediaUri: String?
    public var ttsString: String?
    public var uploadUri: String?
    public var uploadStatus: ININUploadStatus?
    public var hasDefault: Bool?
    public var languageDefault: Bool?
    public var tags: [String:[String]]?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["promptId"] = self.promptId
        nillableDictionary["language"] = self.language
        nillableDictionary["durationSeconds"] = self.durationSeconds
        nillableDictionary["mediaUri"] = self.mediaUri
        nillableDictionary["ttsString"] = self.ttsString
        nillableDictionary["uploadUri"] = self.uploadUri
        nillableDictionary["uploadStatus"] = self.uploadStatus?.rawValue
        nillableDictionary["hasDefault"] = self.hasDefault
        nillableDictionary["languageDefault"] = self.languageDefault
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
