//
// ININTextTableTransform.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTextTableTransform: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var restEndpoint: ININTransformEndpoint?
    public var filenameTransforms: [ININBasicTransform]?
    public var tags: [ININTagModel]?
    public var commentSymbol: String?
    public var delimiter: String?
    public var table: ININTableTransform?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["restEndpoint"] = self.restEndpoint?.encodeToJSON()
        nillableDictionary["filenameTransforms"] = self.filenameTransforms?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["commentSymbol"] = self.commentSymbol
        nillableDictionary["delimiter"] = self.delimiter
        nillableDictionary["table"] = self.table?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
