//
// ININTrunk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTrunk: JSONEncodable {
    public enum ININState: String { 
        case Active = "active"
        case Inactive = "inactive"
        case Deleted = "deleted"
    }
    public enum ININTrunkType: String { 
        case External = "EXTERNAL"
        case Phone = "PHONE"
        case Edge = "EDGE"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var description: String?
    public var version: Int32?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    public var modifiedBy: String?
    public var createdBy: String?
    public var state: ININState?
    public var modifiedByApp: String?
    public var createdByApp: String?
    /** The type of this trunk. */
    public var trunkType: ININTrunkType?
    /** The Edge using this trunk. */
    public var edge: ININUriReference?
    /** The trunk base configuration used on this trunk. */
    public var trunkBase: ININUriReference?
    /** The metabase used to create this trunk. */
    public var trunkMetabase: ININUriReference?
    /** The edge group associated with this trunk. */
    public var edgeGroup: ININUriReference?
    /** True if this trunk is in-service.  This comes from the trunk_enabled property of the referenced trunk base. */
    public var enabled: Bool?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["version"] = self.version?.encodeToJSON()
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["modifiedBy"] = self.modifiedBy
        nillableDictionary["createdBy"] = self.createdBy
        nillableDictionary["state"] = self.state?.rawValue
        nillableDictionary["modifiedByApp"] = self.modifiedByApp
        nillableDictionary["createdByApp"] = self.createdByApp
        nillableDictionary["trunkType"] = self.trunkType?.rawValue
        nillableDictionary["edge"] = self.edge?.encodeToJSON()
        nillableDictionary["trunkBase"] = self.trunkBase?.encodeToJSON()
        nillableDictionary["trunkMetabase"] = self.trunkMetabase?.encodeToJSON()
        nillableDictionary["edgeGroup"] = self.edgeGroup?.encodeToJSON()
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
