//
// ININSearchAggregation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININSearchAggregation: JSONEncodable {
    public enum ININType: String { 
        case Count = "COUNT"
        case Sum = "SUM"
        case Average = "AVERAGE"
        case Contains = "CONTAINS"
        case StartsWith = "STARTS_WITH"
        case EndsWith = "ENDS_WITH"
    }
    public var field: String?
    public var name: String?
    public var type: ININType?
    public var value: String?
    public var size: Int32?
    public var order: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["field"] = self.field
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["value"] = self.value
        nillableDictionary["size"] = self.size?.encodeToJSON()
        nillableDictionary["order"] = self.order?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
