//
// ININRoutingStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININRoutingStatus: JSONEncodable {
    public enum ININStatus: String { 
        case OffQueue = "OFF_QUEUE"
        case Idle = "IDLE"
        case Interacting = "INTERACTING"
        case NotResponding = "NOT_RESPONDING"
        case Communicating = "COMMUNICATING"
    }
    public var userId: String?
    public var status: ININStatus?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var startTime: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["userId"] = self.userId
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["startTime"] = self.startTime?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
