//
// ININTermAttribute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTermAttribute: JSONEncodable {
    public enum ININType: String { 
        case Number = "NUMBER"
        case String = "STRING"
        case Date = "DATE"
        case Boolean = "BOOLEAN"
        case List = "LIST"
    }
    public var id: String?
    public var name: String?
    public var type: ININType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
