//
// ININLocationsSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININLocationsSearchResponse: JSONEncodable {
    public var total: Int64?
    public var pageCount: Int32?
    public var pageSize: Int32?
    public var pageNumber: Int32?
    public var previousPage: String?
    public var currentPage: String?
    public var nextPage: String?
    public var types: [String]?
    public var results: [ININLocation]?
    public var aggregations: [ININLocation]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["pageCount"] = self.pageCount?.encodeToJSON()
        nillableDictionary["pageSize"] = self.pageSize?.encodeToJSON()
        nillableDictionary["pageNumber"] = self.pageNumber?.encodeToJSON()
        nillableDictionary["previousPage"] = self.previousPage
        nillableDictionary["currentPage"] = self.currentPage
        nillableDictionary["nextPage"] = self.nextPage
        nillableDictionary["types"] = self.types?.encodeToJSON()
        nillableDictionary["results"] = self.results?.encodeToJSON()
        nillableDictionary["aggregations"] = self.aggregations?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
