//
// ININEvaluationFormAndScoringSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININEvaluationFormAndScoringSet: JSONEncodable {
    public var evaluationForm: ININEvaluationForm?
    public var answers: ININEvaluationScoringSet?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["evaluationForm"] = self.evaluationForm?.encodeToJSON()
        nillableDictionary["answers"] = self.answers?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
