//
// ININUserPresence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININUserPresence: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Represents the source where the Presence was set. Some examples are: PURECLOUD, LYNC, OUTLOOK, etc. */
    public var source: String?
    /** A boolean used to tell whether or not to set this presence source as the primary on a PATCH */
    public var primary: Bool?
    public var presenceDefinition: ININOrganizationPresence?
    public var message: String?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var modifiedDate: NSDate?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["source"] = self.source
        nillableDictionary["primary"] = self.primary
        nillableDictionary["presenceDefinition"] = self.presenceDefinition?.encodeToJSON()
        nillableDictionary["message"] = self.message
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
