//
// ININResponseQueryRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used to query for responses */
public class ININResponseQueryRequest: JSONEncodable {
    /** Query phrase to search response text and name. If not set will match all. */
    public var queryPhrase: String?
    /** The maximum number of hits to return. Default: 25, Maximum: 500. */
    public var pageSize: Int32?
    /** Filter the query results. */
    public var filters: [ININResponseFilter]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["queryPhrase"] = self.queryPhrase
        nillableDictionary["pageSize"] = self.pageSize?.encodeToJSON()
        nillableDictionary["filters"] = self.filters?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
