//
// ININExtensionPool.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININExtensionPool: JSONEncodable {
    public enum ININState: String { 
        case Active = "active"
        case Inactive = "inactive"
        case Deleted = "deleted"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var description: String?
    public var version: Int32?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    public var modifiedBy: String?
    public var createdBy: String?
    public var state: ININState?
    public var modifiedByApp: String?
    public var createdByApp: String?
    /** The starting phone number for the range of this Extension pool. Must be in E.164 format */
    public var startNumber: String?
    /** The ending phone number for the range of this Extension pool. Must be in E.164 format */
    public var endNumber: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["version"] = self.version?.encodeToJSON()
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["modifiedBy"] = self.modifiedBy
        nillableDictionary["createdBy"] = self.createdBy
        nillableDictionary["state"] = self.state?.rawValue
        nillableDictionary["modifiedByApp"] = self.modifiedByApp
        nillableDictionary["createdByApp"] = self.createdByApp
        nillableDictionary["startNumber"] = self.startNumber
        nillableDictionary["endNumber"] = self.endNumber
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
