//
// ININKeywordSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININKeywordSet: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var description: String?
    public var queue: ININQueue?
    public var language: String?
    public var agents: [ININUser]?
    public var keywords: [ININKeyword]?
    public var participantPurposes: [String]?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["queue"] = self.queue?.encodeToJSON()
        nillableDictionary["language"] = self.language
        nillableDictionary["agents"] = self.agents?.encodeToJSON()
        nillableDictionary["keywords"] = self.keywords?.encodeToJSON()
        nillableDictionary["participantPurposes"] = self.participantPurposes?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
