//
// ININContactSales.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININContactSales: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var email: String?
    public var firstName: String?
    public var lastName: String?
    public var contactPhone: String?
    public var country: String?
    public var title: String?
    public var message: String?
    public var language: String?
    public var productName: String?
    public var quoteId: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["email"] = self.email
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["contactPhone"] = self.contactPhone
        nillableDictionary["country"] = self.country
        nillableDictionary["title"] = self.title
        nillableDictionary["message"] = self.message
        nillableDictionary["language"] = self.language
        nillableDictionary["productName"] = self.productName
        nillableDictionary["quoteId"] = self.quoteId
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
