//
// ININDomainCapabilities.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDomainCapabilities: JSONEncodable {
    public var enabled: Bool?
    public var dhcp: Bool?
    public var metric: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["dhcp"] = self.dhcp
        nillableDictionary["metric"] = self.metric?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
