//
// ININWorkItemDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a WorkItem */
public class ININWorkItemDetails: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var workItemDefinition: ININWorkItemDefinition?
    /** The flow instance ID that created this WorkItem */
    public var flowExecId: ININFlowExecId?
    /** The flow config ID that this workitem was created from. */
    public var flowConfigId: ININFlowConfigId?
    /** The time the flow was started. (that created this workitem). Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var flowCreateTime: NSDate?
    /** The time this workitem was started. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createTime: NSDate?
    /** The user currently working on/has responsibility for this WorkItem.  May be null if no owner. */
    public var owner: ININUser?
    /** List of users that this workItem is offered to.  May be null if only offered to queues. */
    public var offeredToUsers: [ININUser]?
    /** List of queues that this workItem is offered to.  May be null if only offered to users. */
    public var offeredToQueues: [ININQueue]?
    /** The work item title */
    public var title: String?
    /** The work item&#39;s subtitle - 2nd line/description */
    public var subtitle: String?
    /** The documents associated with this workitem */
    public var associatedDocuments: [ININAssociatedDocument]?
    /** The actions that the user can take on this workitem (submit, transfer, etc). */
    public var availableActions: ININWorkItemActions?
    /** The data items that provide values for any work item form elements, if applicable. */
    public var dataValueInfo: ININDataValueInfo?
    /** The data items in the current work item cache, if one exists. */
    public var workItemCache: ININWorkItemCache?
    /** The time this work item was last offered to a user or queue. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var lastOfferedTime: NSDate?
    /** The most recent time a user assumed ownership of a work item. This may be blank if the work item has no owner. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var lastOwnershipUpdateTime: NSDate?
    /** This is the time when the current task that started the work item was started. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var currentTaskStartTime: NSDate?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["workItemDefinition"] = self.workItemDefinition?.encodeToJSON()
        nillableDictionary["flowExecId"] = self.flowExecId?.encodeToJSON()
        nillableDictionary["flowConfigId"] = self.flowConfigId?.encodeToJSON()
        nillableDictionary["flowCreateTime"] = self.flowCreateTime?.encodeToJSON()
        nillableDictionary["createTime"] = self.createTime?.encodeToJSON()
        nillableDictionary["owner"] = self.owner?.encodeToJSON()
        nillableDictionary["offeredToUsers"] = self.offeredToUsers?.encodeToJSON()
        nillableDictionary["offeredToQueues"] = self.offeredToQueues?.encodeToJSON()
        nillableDictionary["title"] = self.title
        nillableDictionary["subtitle"] = self.subtitle
        nillableDictionary["associatedDocuments"] = self.associatedDocuments?.encodeToJSON()
        nillableDictionary["availableActions"] = self.availableActions?.encodeToJSON()
        nillableDictionary["dataValueInfo"] = self.dataValueInfo?.encodeToJSON()
        nillableDictionary["workItemCache"] = self.workItemCache?.encodeToJSON()
        nillableDictionary["lastOfferedTime"] = self.lastOfferedTime?.encodeToJSON()
        nillableDictionary["lastOwnershipUpdateTime"] = self.lastOwnershipUpdateTime?.encodeToJSON()
        nillableDictionary["currentTaskStartTime"] = self.currentTaskStartTime?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
