//
// ININProvisionInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININProvisionInfo: JSONEncodable {
    /** The time at which this phone was provisioned. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var time: NSDate?
    /** The source of the provisioning */
    public var source: String?
    /** The error information from the provision process, if any */
    public var errorInfo: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["time"] = self.time?.encodeToJSON()
        nillableDictionary["source"] = self.source
        nillableDictionary["errorInfo"] = self.errorInfo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
