//
// ININReplaceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININReplaceRequest: JSONEncodable {
    public var changeNumber: Int32?
    public var name: String?
    public var authToken: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["changeNumber"] = self.changeNumber?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["authToken"] = self.authToken
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
