//
// ININPaymentMethod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININPaymentMethod: JSONEncodable {
    public enum ININType: String { 
        case CardToken = "CARD_TOKEN"
    }
    public enum ININCardType: String { 
        case Visa = "Visa"
        case MasterCard = "MasterCard"
        case Discover = "Discover"
        case AmericanExpress = "American Express"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var type: ININType?
    public var providerName: String?
    public var token: String?
    /** for payment methods of type CARD_TOKEN, the card&#39;s expiration date in the format YYYY-MM. */
    public var cardExpirationDate: String?
    public var cardLastFourDigits: String?
    /** for payment methods of type CARD_TOKEN, the type of credit or debit card */
    public var cardType: ININCardType?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["providerName"] = self.providerName
        nillableDictionary["token"] = self.token
        nillableDictionary["cardExpirationDate"] = self.cardExpirationDate
        nillableDictionary["cardLastFourDigits"] = self.cardLastFourDigits
        nillableDictionary["cardType"] = self.cardType?.rawValue
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
