//
// ININGroupTag.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININGroupTag: JSONEncodable {
    public enum ININType: String { 
        case Gistener = "GISTENER"
        case Socialaccount = "SOCIALACCOUNT"
        case Any = "ANY"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Creation date for the entity. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date the entity was last modified. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    /** Defines which entity this Group Tag may be used for.  &#39;ANY&#39; for all entities. */
    public var type: ININType?
    /** Indicates if this Group Tag is available for selection by other entities */
    public var enabled: Bool?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
