//
// ININTableTransform.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTableTransform: JSONEncodable {
    public var headerRow: Int32?
    public var firstData: Int32?
    public var headerReplaces: [ININIndexedTransform]?
    public var columns: [ININIndexedTransform]?
    public var unpivots: [ININUnpivotColumns]?
    public var collapses: [ININColumnCollapse]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["headerRow"] = self.headerRow?.encodeToJSON()
        nillableDictionary["firstData"] = self.firstData?.encodeToJSON()
        nillableDictionary["headerReplaces"] = self.headerReplaces?.encodeToJSON()
        nillableDictionary["columns"] = self.columns?.encodeToJSON()
        nillableDictionary["unpivots"] = self.unpivots?.encodeToJSON()
        nillableDictionary["collapses"] = self.collapses?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
