//
// ININGreetingMediaInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININGreetingMediaInfo: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var mediaFileUri: String?
    public var mediaImageUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["mediaFileUri"] = self.mediaFileUri
        nillableDictionary["mediaImageUri"] = self.mediaImageUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
