//
// ININCallableTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCallableTime: JSONEncodable {
    /** intervals for which it is acceptable to place outbound calls */
    public var timeSlots: [ININCampaignTimeSlot]?
    /** time zone identifier to be applied to the time slots; for example Africa/Abidjan */
    public var timeZoneId: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["timeSlots"] = self.timeSlots?.encodeToJSON()
        nillableDictionary["timeZoneId"] = self.timeZoneId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
