//
// ININFlowBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININFlowBody: JSONEncodable {
    /** The &#39;format&#39; indicates the particular format of the &#39;body&#39; contents.  Reference the Automate documentation for format information. */
    public var format: String?
    /** The flow definition body according to the syntax supported by the &#39;format&#39;.  Use the /processautomation/flows/schemas endpoint to get detailed syntax information for each format. */
    public var body: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["format"] = self.format
        nillableDictionary["body"] = self.body?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
