//
// ININCoverSheet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCoverSheet: JSONEncodable {
    /** Text to be added to the coversheet */
    public var notes: String?
    /** Locale, e.g. &#x3D; en-US */
    public var locale: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["notes"] = self.notes
        nillableDictionary["locale"] = self.locale
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
