//
// ININCampaignSequence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCampaignSequence: JSONEncodable {
    public enum ININStatus: String { 
        case On = "ON"
        case Off = "OFF"
        case Complete = "COMPLETE"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Creation time of the entity. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Last modified time of the entity. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    /** Required for updates, must match the version number of the most recent update */
    public var version: Int32?
    /** the ordered list of campaign identifiers */
    public var campaigns: [ININUriReference]?
    /** the zero-based index of the current campaign in the campaigns list */
    public var currentCampaign: Int32?
    /** status of the sequence */
    public var status: ININStatus?
    /** if a sequence has unexpectedly stopped, this message provides the reason */
    public var stopMessage: String?
    /** indicates if a sequence is to repeat from the beginning after the last campaign completes; default is false */
    public var _repeat: Bool?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["version"] = self.version?.encodeToJSON()
        nillableDictionary["campaigns"] = self.campaigns?.encodeToJSON()
        nillableDictionary["currentCampaign"] = self.currentCampaign?.encodeToJSON()
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["stopMessage"] = self.stopMessage
        nillableDictionary["repeat"] = self._repeat
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
