//
// ININDownloadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDownloadResponse: JSONEncodable {
    public var contentLocationUri: String?
    public var imageUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["contentLocationUri"] = self.contentLocationUri
        nillableDictionary["imageUri"] = self.imageUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
