//
// ININContentFacetFilterItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININContentFacetFilterItem: JSONEncodable {
    public enum ININType: String { 
        case Number = "NUMBER"
        case String = "STRING"
        case Date = "DATE"
        case Boolean = "BOOLEAN"
        case List = "LIST"
    }
    public enum ININOperator: String { 
        case In = "IN"
        case Range = "RANGE"
        case Equals = "EQUALS"
        case Notequals = "NOTEQUALS"
        case Lessthan = "LESSTHAN"
        case Lessthanequals = "LESSTHANEQUALS"
        case Greaterthan = "GREATERTHAN"
        case Greaterthanequals = "GREATERTHANEQUALS"
        case Contains = "CONTAINS"
    }
    public var name: String?
    public var type: ININType?
    public var _operator: ININOperator?
    public var values: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["operator"] = self._operator?.rawValue
        nillableDictionary["values"] = self.values?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
