//
// ININCreateShareRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCreateShareRequest: JSONEncodable {
    public enum ININSharedEntityType: String { 
        case Document = "DOCUMENT"
    }
    public enum ININMemberType: String { 
        case User = "USER"
        case Group = "GROUP"
        case Public = "PUBLIC"
    }
    public var sharedEntityType: ININSharedEntityType?
    public var sharedEntity: ININSharedEntity?
    public var memberType: ININMemberType?
    public var member: ININSharedEntity?
    public var members: [ININCreateShareRequestMember]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sharedEntityType"] = self.sharedEntityType?.rawValue
        nillableDictionary["sharedEntity"] = self.sharedEntity?.encodeToJSON()
        nillableDictionary["memberType"] = self.memberType?.rawValue
        nillableDictionary["member"] = self.member?.encodeToJSON()
        nillableDictionary["members"] = self.members?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
