//
// ININEdgeGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININEdgeGroup: JSONEncodable {
    public enum ININState: String { 
        case Active = "active"
        case Inactive = "inactive"
        case Deleted = "deleted"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var description: String?
    public var version: Int32?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    public var modifiedBy: String?
    public var createdBy: String?
    public var state: ININState?
    public var modifiedByApp: String?
    public var createdByApp: String?
    /** Is this edge group being managed remotely. */
    public var managed: Bool?
    /** A trunk base settings assignment of trunkType \&quot;EDGE\&quot; to use for edge-to-edge communication. */
    public var edgeTrunkBaseAssignment: ININTrunkBaseAssignment?
    /** Trunk base settings assignments of trunkType \&quot;PHONE\&quot; to inherit to edge logical interfaces for phone communication. */
    public var phoneTrunkBaseAssignments: [ININTrunkBaseAssignment]?
    /** Trunk base settings of trunkType \&quot;PHONE\&quot; to inherit to edge logical interface for phone communication. */
    public var phoneTrunkBases: [ININUriReference]?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["version"] = self.version?.encodeToJSON()
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["modifiedBy"] = self.modifiedBy
        nillableDictionary["createdBy"] = self.createdBy
        nillableDictionary["state"] = self.state?.rawValue
        nillableDictionary["modifiedByApp"] = self.modifiedByApp
        nillableDictionary["createdByApp"] = self.createdByApp
        nillableDictionary["managed"] = self.managed
        nillableDictionary["edgeTrunkBaseAssignment"] = self.edgeTrunkBaseAssignment?.encodeToJSON()
        nillableDictionary["phoneTrunkBaseAssignments"] = self.phoneTrunkBaseAssignments?.encodeToJSON()
        nillableDictionary["phoneTrunkBases"] = self.phoneTrunkBases?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
