//
// ININSignatureDocumentInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININSignatureDocumentInfo: JSONEncodable {
    public var org: ININOrganization?
    public var user: ININUser?
    public var returnUrl: String?
    /** Template ID alias for the ESignature template you would like to retrieve. */
    public var template: ININDocusignTemplateMapping?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["org"] = self.org?.encodeToJSON()
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["returnUrl"] = self.returnUrl
        nillableDictionary["template"] = self.template?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
