//
// ININWorkItemTransferRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used as the body to the transferWorkItem request. */
public class ININWorkItemTransferRequest: JSONEncodable {
    public enum ININTransferTargetType: String { 
        case User = "USER"
        case Queue = "QUEUE"
    }
    /** The type of the transferTarget, indicating whether you want to transfer to a User, or a Queue, etc. */
    public var transferTargetType: ININTransferTargetType?
    /** The destination to where the work item should be transferred. */
    public var transferTarget: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["transferTargetType"] = self.transferTargetType?.rawValue
        nillableDictionary["transferTarget"] = self.transferTarget
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
