//
// ININQueueUtilizationDiagnostic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININQueueUtilizationDiagnostic: JSONEncodable {
    /** Identifier of the queue */
    public var queue: ININUriReference?
    /** The number of users joined to the queue */
    public var usersInQueue: Int32?
    /** The number of users active on the queue */
    public var activeUsersInQueue: Int32?
    /** The number of users with a status of on-queue */
    public var usersOnQueue: Int32?
    /** The number of users in the queue currently not engaged */
    public var usersNotUtilized: Int32?
    /** The number of users in the queue with a station */
    public var usersOnQueueWithStation: Int32?
    /** The number of users currently engaged in a campaign call */
    public var usersOnACampaignCall: Int32?
    /** The number of users whose station is homed to an edge different from the campaign */
    public var usersOnDifferentEdgeGroup: Int32?
    /** The number of users currently engaged in a communication that is not part of the campaign */
    public var usersOnANonCampaignCall: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["queue"] = self.queue?.encodeToJSON()
        nillableDictionary["usersInQueue"] = self.usersInQueue?.encodeToJSON()
        nillableDictionary["activeUsersInQueue"] = self.activeUsersInQueue?.encodeToJSON()
        nillableDictionary["usersOnQueue"] = self.usersOnQueue?.encodeToJSON()
        nillableDictionary["usersNotUtilized"] = self.usersNotUtilized?.encodeToJSON()
        nillableDictionary["usersOnQueueWithStation"] = self.usersOnQueueWithStation?.encodeToJSON()
        nillableDictionary["usersOnACampaignCall"] = self.usersOnACampaignCall?.encodeToJSON()
        nillableDictionary["usersOnDifferentEdgeGroup"] = self.usersOnDifferentEdgeGroup?.encodeToJSON()
        nillableDictionary["usersOnANonCampaignCall"] = self.usersOnANonCampaignCall?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
