//
// ININBatchItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININBatchItem: JSONEncodable {
    public var method: String?
    public var url: String?
    public var body: ININBatchItemBody?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["method"] = self.method
        nillableDictionary["url"] = self.url
        nillableDictionary["body"] = self.body?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
