//
// ININFacetResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used as part of the searchResult to return facet results to the caller */
public class ININFacetResult: JSONEncodable {
    public enum ININFieldType: String { 
        case Number = "NUMBER"
        case String = "STRING"
        case Date = "DATE"
        case Boolean = "BOOLEAN"
        case List = "LIST"
        case Group = "GROUP"
    }
    public enum ININRequestType: String { 
        case Term = "TERM"
        case Range = "RANGE"
    }
    /** This was the name passed in as part of the facetRequest */
    public var requestName: String?
    /** The field name that the facet was requested for. */
    public var requestFieldName: String?
    /** data type of the field being returned (if this is a mixed field this will be unknown) */
    public var fieldType: ININFieldType?
    /** the facet request type that was made. */
    public var requestType: ININRequestType?
    public var results: [ININFacetResultItem]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["requestName"] = self.requestName
        nillableDictionary["requestFieldName"] = self.requestFieldName
        nillableDictionary["fieldType"] = self.fieldType?.rawValue
        nillableDictionary["requestType"] = self.requestType?.rawValue
        nillableDictionary["results"] = self.results?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
