//
// ININVoicemailMessageEntityListing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININVoicemailMessageEntityListing: JSONEncodable {
    public var total: Int64?
    public var entities: [ININVoicemailMessage]?
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["entities"] = self.entities?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
