//
// ININFaxSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININFaxSummary: JSONEncodable {
    public var readCount: Int32?
    public var unreadCount: Int32?
    public var totalCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["readCount"] = self.readCount?.encodeToJSON()
        nillableDictionary["unreadCount"] = self.unreadCount?.encodeToJSON()
        nillableDictionary["totalCount"] = self.totalCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
