//
// ININUserActionMetadataEntityListing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININUserActionMetadataEntityListing: JSONEncodable {
    public var pageSize: Int32?
    public var pageNumber: Int32?
    public var entities: [ININUserActionMetadata]?
    public var selfUri: String?
    public var previousUri: String?
    public var firstUri: String?
    public var nextUri: String?
    public var pageCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["pageSize"] = self.pageSize?.encodeToJSON()
        nillableDictionary["pageNumber"] = self.pageNumber?.encodeToJSON()
        nillableDictionary["entities"] = self.entities?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        nillableDictionary["previousUri"] = self.previousUri
        nillableDictionary["firstUri"] = self.firstUri
        nillableDictionary["nextUri"] = self.nextUri
        nillableDictionary["pageCount"] = self.pageCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
