//
// ININDeltaDocument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDeltaDocument: JSONEncodable {
    public enum ININOperation: String { 
        case Created = "CREATED"
        case Updated = "UPDATED"
        case Replaced = "REPLACED"
        case Deleted = "DELETED"
    }
    public var id: String?
    public var name: String?
    public var filename: String?
    public var contentType: String?
    public var contentLengthBytes: Int64?
    public var operation: ININOperation?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["filename"] = self.filename
        nillableDictionary["contentType"] = self.contentType
        nillableDictionary["contentLengthBytes"] = self.contentLengthBytes?.encodeToJSON()
        nillableDictionary["operation"] = self.operation?.rawValue
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
