//
// ININCallRecord.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCallRecord: JSONEncodable {
    /** Timestamp of the last attempt to reach this number. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var lastAttempt: NSDate?
    /** Result of the last attempt to reach this number */
    public var lastResult: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["lastAttempt"] = self.lastAttempt?.encodeToJSON()
        nillableDictionary["lastResult"] = self.lastResult
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
