//
// ININSocialAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININSocialAccount: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Creation date for the entity. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date the entity was last modified. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    /** Indicates if this Social Account is available for selection by other entities */
    public var enabled: Bool?
    /** True when successfully completing the third-party authorization process */
    public var authorized: Bool?
    /** Which third party Social Media Hub this account will be communicating through */
    public var socialHub: String?
    /** Credential provided through the Social Hub&#39;s authorization process */
    public var accessToken: String?
    /** Credential provided through the Social Hub&#39;s authorization process */
    public var accessTokenSecret: String?
    /** The account ID as provided by Twitter during the authorization process */
    public var twitterId: String?
    /** Indicates if a stream should be opened on behalf of the indicated Social Hub account */
    public var streamingEnabled: Bool?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["authorized"] = self.authorized
        nillableDictionary["socialHub"] = self.socialHub
        nillableDictionary["access_token"] = self.accessToken
        nillableDictionary["access_token_secret"] = self.accessTokenSecret
        nillableDictionary["twitterId"] = self.twitterId
        nillableDictionary["streamingEnabled"] = self.streamingEnabled
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
