//
// ININKeyRotationSchedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININKeyRotationSchedule: JSONEncodable {
    public enum ININPeriod: String { 
        case Disabled = "DISABLED"
        case Daily = "DAILY"
        case Weekly = "WEEKLY"
        case Monthly = "MONTHLY"
        case Yearly = "YEARLY"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Value to set schedule to */
    public var period: ININPeriod?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["period"] = self.period?.rawValue
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
