//
// ININVoicemailMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININVoicemailMessage: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var conversation: ININConversation?
    public var read: Bool?
    public var audioRecordingDurationSeconds: Int32?
    public var audioRecordingSizeBytes: Int64?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createdDate: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var modifiedDate: NSDate?
    public var callerAddress: String?
    public var callerName: String?
    public var callerUser: ININUser?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["conversation"] = self.conversation?.encodeToJSON()
        nillableDictionary["read"] = self.read
        nillableDictionary["audioRecordingDurationSeconds"] = self.audioRecordingDurationSeconds?.encodeToJSON()
        nillableDictionary["audioRecordingSizeBytes"] = self.audioRecordingSizeBytes?.encodeToJSON()
        nillableDictionary["createdDate"] = self.createdDate?.encodeToJSON()
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        nillableDictionary["callerAddress"] = self.callerAddress
        nillableDictionary["callerName"] = self.callerName
        nillableDictionary["callerUser"] = self.callerUser?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
