//
// ININCalibration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCalibration: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var calibrator: ININUser?
    public var agent: ININUser?
    public var conversation: ININConversation?
    public var evaluationForm: ININEvaluationForm?
    public var contextId: String?
    public var averageScore: Int32?
    public var highScore: Int32?
    public var lowScore: Int32?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createdDate: NSDate?
    public var evaluations: [ININEvaluation]?
    public var evaluators: [ININUser]?
    public var scoringIndex: ININEvaluation?
    public var expertEvaluator: ININUser?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["calibrator"] = self.calibrator?.encodeToJSON()
        nillableDictionary["agent"] = self.agent?.encodeToJSON()
        nillableDictionary["conversation"] = self.conversation?.encodeToJSON()
        nillableDictionary["evaluationForm"] = self.evaluationForm?.encodeToJSON()
        nillableDictionary["contextId"] = self.contextId
        nillableDictionary["averageScore"] = self.averageScore?.encodeToJSON()
        nillableDictionary["highScore"] = self.highScore?.encodeToJSON()
        nillableDictionary["lowScore"] = self.lowScore?.encodeToJSON()
        nillableDictionary["createdDate"] = self.createdDate?.encodeToJSON()
        nillableDictionary["evaluations"] = self.evaluations?.encodeToJSON()
        nillableDictionary["evaluators"] = self.evaluators?.encodeToJSON()
        nillableDictionary["scoringIndex"] = self.scoringIndex?.encodeToJSON()
        nillableDictionary["expertEvaluator"] = self.expertEvaluator?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
