//
// ININXlsxSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININXlsxSchema: JSONEncodable {
    /** A list of all the schemas for a XLSX file. Each schema represents a different sheet&#39;s schema. */
    public var sheetSchemas: [ININSheetSchema]?
    /** Human readable name for schema. */
    public var name: String?
    /** Carrier ID associated with this CSV schema. */
    public var carrierId: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["SheetSchemas"] = self.sheetSchemas?.encodeToJSON()
        nillableDictionary["Name"] = self.name
        nillableDictionary["CarrierId"] = self.carrierId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
