//
// ININTrunkRecordingEnabledCount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTrunkRecordingEnabledCount: JSONEncodable {
    /** The amount of trunks that have recording enabled */
    public var enabledCount: Int32?
    /** The amount of trunks that do not have recording enabled */
    public var disabledCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["enabledCount"] = self.enabledCount?.encodeToJSON()
        nillableDictionary["disabledCount"] = self.disabledCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
