//
// ININVideo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININVideo: JSONEncodable {
    public enum ININState: String { 
        case Alerting = "ALERTING"
        case Dialing = "DIALING"
        case Contacting = "CONTACTING"
        case Offering = "OFFERING"
        case Connected = "CONNECTED"
        case Disconnected = "DISCONNECTED"
        case Terminated = "TERMINATED"
        case None = "NONE"
    }
    public enum ININDisconnectType: String { 
        case Endpoint = "ENDPOINT"
        case Client = "CLIENT"
        case System = "SYSTEM"
        case Transfer = "TRANSFER"
        case TransferConference = "TRANSFER_CONFERENCE"
        case TransferConsult = "TRANSFER_CONSULT"
        case TransferForward = "TRANSFER_FORWARD"
        case Error = "ERROR"
        case Peer = "PEER"
        case Other = "OTHER"
    }
    public var state: ININState?
    public var id: String?
    public var context: String?
    public var audioMuted: Bool?
    public var videoMuted: Bool?
    public var sharingScreen: Bool?
    public var peerCount: Int32?
    public var disconnectType: ININDisconnectType?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var connectedTime: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var disconnectedTime: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["state"] = self.state?.rawValue
        nillableDictionary["id"] = self.id
        nillableDictionary["context"] = self.context
        nillableDictionary["audioMuted"] = self.audioMuted
        nillableDictionary["videoMuted"] = self.videoMuted
        nillableDictionary["sharingScreen"] = self.sharingScreen
        nillableDictionary["peerCount"] = self.peerCount?.encodeToJSON()
        nillableDictionary["disconnectType"] = self.disconnectType?.rawValue
        nillableDictionary["connectedTime"] = self.connectedTime?.encodeToJSON()
        nillableDictionary["disconnectedTime"] = self.disconnectedTime?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
