//
// ININService.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININService: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var status: String?
    /** An inbound carrier specific domain (i.e. lb.domain.com) */
    public var domains: [String]?
    public var serviceTypes: [ININServiceType]?
    public var gateways: [ININGateway]?
    public var dns: ININDns?
    public var vpn: ININVpn?
    public var carrier: ININCarrier?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["status"] = self.status
        nillableDictionary["domains"] = self.domains?.encodeToJSON()
        nillableDictionary["serviceTypes"] = self.serviceTypes?.encodeToJSON()
        nillableDictionary["gateways"] = self.gateways?.encodeToJSON()
        nillableDictionary["dns"] = self.dns?.encodeToJSON()
        nillableDictionary["vpn"] = self.vpn?.encodeToJSON()
        nillableDictionary["carrier"] = self.carrier?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
