//
// ININFlowVersionConfigMetaData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a specific Flow Definition version. */
public class ININFlowVersionConfigMetaData: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Checkin comment for this specific flow version. */
    public var versionSpecificComment: String?
    /** Uri location for the flow definition contents. */
    public var flowDefinitionUri: String?
    /** If known, the user who created this flow version. */
    public var createdByUser: ININUser?
    /** The date and time that the version was created. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createdDate: NSDate?
    /** The URI for this object */
    public var selfUri: String?
    /** Version of this flow config. */
    public var version: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["versionSpecificComment"] = self.versionSpecificComment
        nillableDictionary["flowDefinitionUri"] = self.flowDefinitionUri
        nillableDictionary["createdByUser"] = self.createdByUser?.encodeToJSON()
        nillableDictionary["createdDate"] = self.createdDate?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        nillableDictionary["version"] = self.version
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
