//
// ININChatMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININChatMessage: JSONEncodable {
    public var body: String?
    public var id: String?
    public var to: String?
    public var from: String?
    public var utc: String?
    public var chat: String?
    public var message: String?
    public var type: String?
    public var user: ININChatMessageUser?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["body"] = self.body
        nillableDictionary["id"] = self.id
        nillableDictionary["to"] = self.to
        nillableDictionary["from"] = self.from
        nillableDictionary["utc"] = self.utc
        nillableDictionary["chat"] = self.chat
        nillableDictionary["message"] = self.message
        nillableDictionary["type"] = self.type
        nillableDictionary["user"] = self.user?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
