//
// ININDisconnectReason.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDisconnectReason: JSONEncodable {
    public enum ININType: String { 
        case Q850 = "Q_850"
        case Sip = "SIP"
    }
    public var type: ININType?
    public var code: Int32?
    public var phrase: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["code"] = self.code?.encodeToJSON()
        nillableDictionary["phrase"] = self.phrase
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
