//
// ININBasicTransform.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININBasicTransform: JSONEncodable {
    public var replaces: [ININTransformLens]?
    public var entityPath: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["replaces"] = self.replaces?.encodeToJSON()
        nillableDictionary["entityPath"] = self.entityPath?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
