//
// ININPolicyConditions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININPolicyConditions: JSONEncodable {
    public var forUsers: [ININUser]?
    public var directions: [String]?
    public var dateRanges: [String]?
    public var mediaTypes: [String]?
    public var forQueues: [ININQueue]?
    public var duration: ININDurationCondition?
    public var wrapupCodes: [ININWrapupCode]?
    public var timeAllowed: ININTimeAllowed?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["forUsers"] = self.forUsers?.encodeToJSON()
        nillableDictionary["directions"] = self.directions?.encodeToJSON()
        nillableDictionary["dateRanges"] = self.dateRanges?.encodeToJSON()
        nillableDictionary["mediaTypes"] = self.mediaTypes?.encodeToJSON()
        nillableDictionary["forQueues"] = self.forQueues?.encodeToJSON()
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["wrapupCodes"] = self.wrapupCodes?.encodeToJSON()
        nillableDictionary["timeAllowed"] = self.timeAllowed?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
