//
// ININDocumentAudit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDocumentAudit: JSONEncodable {
    public enum ININLevel: String { 
        case User = "USER"
        case System = "SYSTEM"
    }
    public enum ININStatus: String { 
        case Success = "SUCCESS"
        case Failure = "FAILURE"
    }
    public enum ININActionContext: String { 
        case Create = "CREATE"
        case Read = "READ"
        case Update = "UPDATE"
        case Delete = "DELETE"
        case Download = "DOWNLOAD"
        case View = "VIEW"
        case Upload = "UPLOAD"
        case Save = "SAVE"
        case Move = "MOVE"
        case Copy = "COPY"
        case Add = "ADD"
        case Remove = "REMOVE"
        case Receive = "RECEIVE"
        case Convert = "CONVERT"
        case Fax = "FAX"
        case CreateCoverpage = "CREATE_COVERPAGE"
        case UserAdd = "USER_ADD"
        case UserRemove = "USER_REMOVE"
        case MemberAdd = "MEMBER_ADD"
        case MemberRemove = "MEMBER_REMOVE"
        case MemberUpdate = "MEMBER_UPDATE"
        case TagAdd = "TAG_ADD"
        case TagRemove = "TAG_REMOVE"
        case TagUpdate = "TAG_UPDATE"
        case AttributeAdd = "ATTRIBUTE_ADD"
        case AttributeRemove = "ATTRIBUTE_REMOVE"
        case AttributeUpdate = "ATTRIBUTE_UPDATE"
        case AttributeGroupInstanceAdd = "ATTRIBUTE_GROUP_INSTANCE_ADD"
        case AttributeGroupInstanceRemove = "ATTRIBUTE_GROUP_INSTANCE_REMOVE"
        case AttributeGroupInstanceUpdate = "ATTRIBUTE_GROUP_INSTANCE_UPDATE"
        case IndexSave = "INDEX_SAVE"
        case IndexDelete = "INDEX_DELETE"
        case IndexCreate = "INDEX_CREATE"
        case FileSave = "FILE_SAVE"
        case FileDelete = "FILE_DELETE"
        case FileRead = "FILE_READ"
        case ThumbnailCreate = "THUMBNAIL_CREATE"
        case TextExtract = "TEXT_EXTRACT"
        case ShareAdd = "SHARE_ADD"
        case ShareRemove = "SHARE_REMOVE"
        case VersionCreate = "VERSION_CREATE"
    }
    public enum ININAction: String { 
        case Create = "CREATE"
        case Read = "READ"
        case Update = "UPDATE"
        case Delete = "DELETE"
        case Download = "DOWNLOAD"
        case View = "VIEW"
        case Upload = "UPLOAD"
        case Save = "SAVE"
        case Move = "MOVE"
        case Copy = "COPY"
        case Add = "ADD"
        case Remove = "REMOVE"
        case Receive = "RECEIVE"
        case Convert = "CONVERT"
        case Fax = "FAX"
        case CreateCoverpage = "CREATE_COVERPAGE"
        case UserAdd = "USER_ADD"
        case UserRemove = "USER_REMOVE"
        case MemberAdd = "MEMBER_ADD"
        case MemberRemove = "MEMBER_REMOVE"
        case MemberUpdate = "MEMBER_UPDATE"
        case TagAdd = "TAG_ADD"
        case TagRemove = "TAG_REMOVE"
        case TagUpdate = "TAG_UPDATE"
        case AttributeAdd = "ATTRIBUTE_ADD"
        case AttributeRemove = "ATTRIBUTE_REMOVE"
        case AttributeUpdate = "ATTRIBUTE_UPDATE"
        case AttributeGroupInstanceAdd = "ATTRIBUTE_GROUP_INSTANCE_ADD"
        case AttributeGroupInstanceRemove = "ATTRIBUTE_GROUP_INSTANCE_REMOVE"
        case AttributeGroupInstanceUpdate = "ATTRIBUTE_GROUP_INSTANCE_UPDATE"
        case IndexSave = "INDEX_SAVE"
        case IndexDelete = "INDEX_DELETE"
        case IndexCreate = "INDEX_CREATE"
        case FileSave = "FILE_SAVE"
        case FileDelete = "FILE_DELETE"
        case FileRead = "FILE_READ"
        case ThumbnailCreate = "THUMBNAIL_CREATE"
        case TextExtract = "TEXT_EXTRACT"
        case ShareAdd = "SHARE_ADD"
        case ShareRemove = "SHARE_REMOVE"
        case VersionCreate = "VERSION_CREATE"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var user: ININUriReference?
    public var workspace: ININUriReference?
    public var transactionId: String?
    public var transactionInitiator: Bool?
    public var application: String?
    public var serviceName: String?
    public var level: ININLevel?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var timestamp: NSDate?
    public var status: ININStatus?
    public var actionContext: ININActionContext?
    public var action: ININAction?
    public var entity: ININAuditEntityReference?
    public var changes: [ININAuditChange]?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["workspace"] = self.workspace?.encodeToJSON()
        nillableDictionary["transactionId"] = self.transactionId
        nillableDictionary["transactionInitiator"] = self.transactionInitiator
        nillableDictionary["application"] = self.application
        nillableDictionary["serviceName"] = self.serviceName
        nillableDictionary["level"] = self.level?.rawValue
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["actionContext"] = self.actionContext?.rawValue
        nillableDictionary["action"] = self.action?.rawValue
        nillableDictionary["entity"] = self.entity?.encodeToJSON()
        nillableDictionary["changes"] = self.changes?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
