//
// ININReportRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used to perform a search on various data stored in search engines */
public class ININReportRequest: JSONEncodable {
    /** The pageNumber to get results from (EG If there are 100 results with a pageSize of 10 and pageNumber is 3 then 10 results will be returned starting with index #31 */
    public var pageNumber: Int32?
    /** Number of entries to return/calculate per page. */
    public var pageSize: Int32?
    /** List of facet requests to generate summary views from the report result set (if any) */
    public var facetRequests: [ININFacetRequest]?
    /** sort the results on a field(s) */
    public var sort: [ININSortField]?
    /** You can also restrict the request to particular field values and ranges */
    public var filters: [ININFilterItem]?
    public var groupBy: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["pageNumber"] = self.pageNumber?.encodeToJSON()
        nillableDictionary["pageSize"] = self.pageSize?.encodeToJSON()
        nillableDictionary["facetRequests"] = self.facetRequests?.encodeToJSON()
        nillableDictionary["sort"] = self.sort?.encodeToJSON()
        nillableDictionary["filters"] = self.filters?.encodeToJSON()
        nillableDictionary["groupBy"] = self.groupBy?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
