//
// ININFlowHistoryDataItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Data elements associated with a history event */
public class ININFlowHistoryDataItem: JSONEncodable {
    /** The name of the data element associated with a history event. */
    public var parameterName: String?
    /** The type of the data element associated with a history event. */
    public var parameterType: String?
    /** The values of the data element associated with a history event. */
    public var parameterValues: ININValue?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["parameterName"] = self.parameterName
        nillableDictionary["parameterType"] = self.parameterType
        nillableDictionary["parameterValues"] = self.parameterValues?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
