//
// ININAnalyticsEvaluation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININAnalyticsEvaluation: JSONEncodable {
    public var evaluationId: String?
    public var evaluatorId: String?
    public var userId: String?
    public var eventTime: String?
    public var queueId: String?
    public var formId: String?
    public var contextId: String?
    public var formName: String?
    public var getoTotalScore: Int64?
    public var getoTotalCriticalScore: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["evaluationId"] = self.evaluationId
        nillableDictionary["evaluatorId"] = self.evaluatorId
        nillableDictionary["userId"] = self.userId
        nillableDictionary["eventTime"] = self.eventTime
        nillableDictionary["queueId"] = self.queueId
        nillableDictionary["formId"] = self.formId
        nillableDictionary["contextId"] = self.contextId
        nillableDictionary["formName"] = self.formName
        nillableDictionary["getoTotalScore"] = self.getoTotalScore?.encodeToJSON()
        nillableDictionary["getoTotalCriticalScore"] = self.getoTotalCriticalScore?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
