//
// ININCodesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCodesRequest: JSONEncodable {
    public var organizationId: String?
    public var addCommunicationCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["organizationId"] = self.organizationId
        nillableDictionary["addCommunicationCode"] = self.addCommunicationCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
