//
// ININIntegrationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Descriptor for a type of Integration. */
public class ININIntegrationType: JSONEncodable {
    /** The ID of the integration type. */
    public var id: String?
    public var name: String?
    /** Localized description of the integration type. */
    public var description: String?
    /** PureCloud provider of the integration type. */
    public var provider: String?
    /** Collection of logos. */
    public var images: [ININUserImage]?
    /** URI of the schema describing the key-value properties needed to configure an integration of this type. */
    public var configPropertiesSchemaUri: String?
    /** URI of the schema describing the advanced JSON document needed to configure an integration of this type. */
    public var configAdvancedSchemaUri: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["provider"] = self.provider
        nillableDictionary["images"] = self.images?.encodeToJSON()
        nillableDictionary["configPropertiesSchemaUri"] = self.configPropertiesSchemaUri
        nillableDictionary["configAdvancedSchemaUri"] = self.configAdvancedSchemaUri
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
