//
// ININAccountStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININAccountStatus: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var orgName: String?
    public var configured: Bool?
    public var adminUIURL: String?
    public var thirdPartyAccountId: String?
    public var thirdPartySubscriptionId: String?
    public var thirdPartySubscriptionNonAcbId: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["orgName"] = self.orgName
        nillableDictionary["configured"] = self.configured
        nillableDictionary["adminUIURL"] = self.adminUIURL
        nillableDictionary["thirdPartyAccountId"] = self.thirdPartyAccountId
        nillableDictionary["thirdPartySubscriptionId"] = self.thirdPartySubscriptionId
        nillableDictionary["thirdPartySubscriptionNonAcbId"] = self.thirdPartySubscriptionNonAcbId
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
