//
// ININSearchCriteria.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININSearchCriteria: JSONEncodable {
    public enum ININOperator: String { 
        case And = "AND"
        case Or = "OR"
        case Not = "NOT"
    }
    public enum ININType: String { 
        case Exact = "EXACT"
        case Contains = "CONTAINS"
        case StartsWith = "STARTS_WITH"
        case RequiredFields = "REQUIRED_FIELDS"
        case Range = "RANGE"
        case DateRange = "DATE_RANGE"
        case LessThan = "LESS_THAN"
        case LessThanEqualTo = "LESS_THAN_EQUAL_TO"
        case GreaterThan = "GREATER_THAN"
        case GreaterThanEqualTo = "GREATER_THAN_EQUAL_TO"
        case Simple = "SIMPLE"
        case Term = "TERM"
        case Terms = "TERMS"
        case QueryString = "QUERY_STRING"
    }
    public var endValue: String?
    public var values: [String]?
    public var startValue: String?
    public var fields: [String]?
    public var value: String?
    public var _operator: ININOperator?
    public var group: [ININSearchCriteria]?
    public var type: ININType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["endValue"] = self.endValue
        nillableDictionary["values"] = self.values?.encodeToJSON()
        nillableDictionary["startValue"] = self.startValue
        nillableDictionary["fields"] = self.fields?.encodeToJSON()
        nillableDictionary["value"] = self.value
        nillableDictionary["operator"] = self._operator?.rawValue
        nillableDictionary["group"] = self.group?.encodeToJSON()
        nillableDictionary["type"] = self.type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
