//
// ININDomainPermission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDomainPermission: JSONEncodable {
    public var domain: String?
    public var entityType: String?
    public var action: String?
    public var label: String?
    public var allowsConditions: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["domain"] = self.domain
        nillableDictionary["entityType"] = self.entityType
        nillableDictionary["action"] = self.action
        nillableDictionary["label"] = self.label
        nillableDictionary["allowsConditions"] = self.allowsConditions
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
