//
// ININLockInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININLockInfo: JSONEncodable {
    public enum ININAction: String { 
        case Update = "UPDATE"
        case Delete = "DELETE"
        case Copy = "COPY"
        case Move = "MOVE"
        case Replace = "REPLACE"
        case Thumbnail = "THUMBNAIL"
        case TextExtraction = "TEXT_EXTRACTION"
    }
    public var lockedBy: ININUriReference?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateExpires: NSDate?
    public var action: ININAction?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["lockedBy"] = self.lockedBy?.encodeToJSON()
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateExpires"] = self.dateExpires?.encodeToJSON()
        nillableDictionary["action"] = self.action?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
