//
// ININGreetingAudioFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININGreetingAudioFile: JSONEncodable {
    public var durationMilliseconds: Int64?
    public var sizeBytes: Int64?
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["durationMilliseconds"] = self.durationMilliseconds?.encodeToJSON()
        nillableDictionary["sizeBytes"] = self.sizeBytes?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
