//
// ININMediaResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININMediaResult: JSONEncodable {
    public var mediaUri: String?
    public var waveformData: [Float]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["mediaUri"] = self.mediaUri
        nillableDictionary["waveformData"] = self.waveformData?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
