//
// ININScript.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININScript: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var versionId: String?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createdDate: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var modifiedDate: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var publishedDate: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var versionDate: NSDate?
    public var startPageId: String?
    public var startPageName: String?
    public var features: AnyObject?
    public var variables: AnyObject?
    public var customActions: AnyObject?
    public var pages: [ININPage]?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["versionId"] = self.versionId
        nillableDictionary["createdDate"] = self.createdDate?.encodeToJSON()
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        nillableDictionary["publishedDate"] = self.publishedDate?.encodeToJSON()
        nillableDictionary["versionDate"] = self.versionDate?.encodeToJSON()
        nillableDictionary["startPageId"] = self.startPageId
        nillableDictionary["startPageName"] = self.startPageName
        nillableDictionary["features"] = self.features
        nillableDictionary["variables"] = self.variables
        nillableDictionary["customActions"] = self.customActions
        nillableDictionary["pages"] = self.pages?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
