//
// ININPhoneBase.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININPhoneBase: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Phone Meta Base */
    public var phoneMetaBase: ININUriReference?
    /** Lines */
    public var lines: [ININLineBase]?
    public var properties: [String:AnyObject]?
    public var capabilities: ININPhoneCapabilities?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["phoneMetaBase"] = self.phoneMetaBase?.encodeToJSON()
        nillableDictionary["lines"] = self.lines?.encodeToJSON()
        nillableDictionary["properties"] = self.properties?.encodeToJSON()
        nillableDictionary["capabilities"] = self.capabilities?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
