//
// ININTrace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTrace: JSONEncodable {
    public enum ININLevel: String { 
        case Error = "ERROR"
        case Warn = "WARN"
        case Info = "INFO"
        case Debug = "DEBUG"
    }
    public var topic: String?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var timestamp: NSDate?
    public var level: ININLevel?
    public var message: String?
    public var details: AnyObject?
    public var timestampString: String?
    public var detailsString: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["topic"] = self.topic
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        nillableDictionary["level"] = self.level?.rawValue
        nillableDictionary["message"] = self.message
        nillableDictionary["details"] = self.details
        nillableDictionary["timestampString"] = self.timestampString
        nillableDictionary["detailsString"] = self.detailsString
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
