//
// ININAnalyticsParticipant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININAnalyticsParticipant: JSONEncodable {
    public enum ININPurpose: String { 
        case Manual = "manual"
        case Dialer = "dialer"
        case Inbound = "inbound"
        case Acd = "acd"
        case Ivr = "ivr"
        case Voicemail = "voicemail"
        case Outbound = "outbound"
        case Agent = "agent"
        case User = "user"
        case Station = "station"
        case Group = "group"
        case Customer = "customer"
        case External = "external"
    }
    public var participantId: String?
    public var participantName: String?
    public var userId: String?
    public var purpose: ININPurpose?
    public var sessions: [ININAnalyticsSession]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["participantId"] = self.participantId
        nillableDictionary["participantName"] = self.participantName
        nillableDictionary["userId"] = self.userId
        nillableDictionary["purpose"] = self.purpose?.rawValue
        nillableDictionary["sessions"] = self.sessions?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
