//
// ININFlowInputData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** launch parameters or initializations for variables in the flow. */
public class ININFlowInputData: JSONEncodable {
    /** A list of document IDs to link with the new flow instance. */
    public var linkedDocumentIds: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["linkedDocumentIds"] = self.linkedDocumentIds?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
