//
// ININSortField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININSortField: JSONEncodable {
    public enum ININSortType: String { 
        case Ascending = "ASCENDING"
        case Descending = "DESCENDING"
    }
    public var name: String?
    public var sortType: ININSortType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["sortType"] = self.sortType?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
