//
// ININPredictionResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININPredictionResults: JSONEncodable {
    public enum ININFormula: String { 
        case Best = "BEST"
        case Simple = "SIMPLE"
        case Abandon = "ABANDON"
        case Patienceabandon = "PATIENCEABANDON"
    }
    /** Indicates the estimated wait time Formula */
    public var formula: ININFormula?
    /** Estimated wait time in seconds */
    public var estimatedWaitTimeSeconds: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["formula"] = self.formula?.rawValue
        nillableDictionary["estimatedWaitTimeSeconds"] = self.estimatedWaitTimeSeconds?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
