//
// ININOrgMediaUtilization.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININOrgMediaUtilization: JSONEncodable {
    /** Defines the maximum number of conversations of this type that an agent can handle at one time. */
    public var maximumCapacity: Int32?
    /** Defines the list of other media types that can interrupt a conversation of this media type.  Values can be: call, chat, email, or socialExpression */
    public var interruptableMediaTypes: [String]?
    /** If true, then track non-ACD conversations against utilization */
    public var includeNonAcd: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["maximumCapacity"] = self.maximumCapacity?.encodeToJSON()
        nillableDictionary["interruptableMediaTypes"] = self.interruptableMediaTypes?.encodeToJSON()
        nillableDictionary["includeNonAcd"] = self.includeNonAcd
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
