//
// ININAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININAccount: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var orgLegalName: String?
    public var billingAddressLine1: String?
    public var billingAddressLine2: String?
    public var billingAddressCity: String?
    public var billingAddressState: String?
    public var billingAddressZipCode: String?
    public var billingAddressCountry: String?
    public var legalAddressLine1: String?
    public var legalAddressLine2: String?
    public var legalAddressCity: String?
    public var legalAddressState: String?
    public var legalAddressZipCode: String?
    public var legalAddressCountry: String?
    public var billingContactFirstName: String?
    public var billingContactLastName: String?
    public var billingContactEmail: String?
    public var billingContactPhone: String?
    public var purchaseOrderNumber: String?
    public var isTaxExempt: Bool?
    public var currency: String?
    public var paymentTerm: String?
    public var contractTerm: Int32?
    public var autoRenew: Bool?
    public var enabled: Bool?
    public var minCommitQuantities: [String:Int32]?
    public var estimatedQuantities: [String:Int32]?
    public var oneTimeCharges: [String]?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["orgLegalName"] = self.orgLegalName
        nillableDictionary["billingAddressLine1"] = self.billingAddressLine1
        nillableDictionary["billingAddressLine2"] = self.billingAddressLine2
        nillableDictionary["billingAddressCity"] = self.billingAddressCity
        nillableDictionary["billingAddressState"] = self.billingAddressState
        nillableDictionary["billingAddressZipCode"] = self.billingAddressZipCode
        nillableDictionary["billingAddressCountry"] = self.billingAddressCountry
        nillableDictionary["legalAddressLine1"] = self.legalAddressLine1
        nillableDictionary["legalAddressLine2"] = self.legalAddressLine2
        nillableDictionary["legalAddressCity"] = self.legalAddressCity
        nillableDictionary["legalAddressState"] = self.legalAddressState
        nillableDictionary["legalAddressZipCode"] = self.legalAddressZipCode
        nillableDictionary["legalAddressCountry"] = self.legalAddressCountry
        nillableDictionary["billingContactFirstName"] = self.billingContactFirstName
        nillableDictionary["billingContactLastName"] = self.billingContactLastName
        nillableDictionary["billingContactEmail"] = self.billingContactEmail
        nillableDictionary["billingContactPhone"] = self.billingContactPhone
        nillableDictionary["purchaseOrderNumber"] = self.purchaseOrderNumber
        nillableDictionary["isTaxExempt"] = self.isTaxExempt
        nillableDictionary["currency"] = self.currency
        nillableDictionary["paymentTerm"] = self.paymentTerm
        nillableDictionary["contractTerm"] = self.contractTerm?.encodeToJSON()
        nillableDictionary["autoRenew"] = self.autoRenew
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["minCommitQuantities"] = self.minCommitQuantities?.encodeToJSON()
        nillableDictionary["estimatedQuantities"] = self.estimatedQuantities?.encodeToJSON()
        nillableDictionary["oneTimeCharges"] = self.oneTimeCharges?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
