//
// ININMeteredEvaluationAssignment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININMeteredEvaluationAssignment: JSONEncodable {
    public var evaluationContextId: String?
    public var evaluators: [ININUser]?
    public var maxNumberEvaluations: Int32?
    public var evaluationForm: ININEvaluationForm?
    public var assignToActiveUser: Bool?
    public var timeInterval: ININTimeInterval?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["evaluationContextId"] = self.evaluationContextId
        nillableDictionary["evaluators"] = self.evaluators?.encodeToJSON()
        nillableDictionary["maxNumberEvaluations"] = self.maxNumberEvaluations?.encodeToJSON()
        nillableDictionary["evaluationForm"] = self.evaluationForm?.encodeToJSON()
        nillableDictionary["assignToActiveUser"] = self.assignToActiveUser
        nillableDictionary["timeInterval"] = self.timeInterval?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
