//
// ININPolicy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININPolicy: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var modifiedDate: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createdDate: NSDate?
    public var order: Int32?
    public var description: String?
    public var enabled: Bool?
    /** Conditions and actions per media type */
    public var mediaPolicies: ININMediaPolicies?
    /** Conditions */
    public var conditions: ININPolicyConditions?
    /** Actions */
    public var actions: ININPolicyActions?
    public var policyErrors: ININPolicyErrors?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        nillableDictionary["createdDate"] = self.createdDate?.encodeToJSON()
        nillableDictionary["order"] = self.order?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["mediaPolicies"] = self.mediaPolicies?.encodeToJSON()
        nillableDictionary["conditions"] = self.conditions?.encodeToJSON()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["policyErrors"] = self.policyErrors?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
