//
// ININScene.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININScene: JSONEncodable {
    public enum ININType: String { 
        case Primary = "PRIMARY"
        case Secondary = "SECONDARY"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var sceneGroup: ININSceneGroup?
    public var assets: [ININAsset]?
    public var thumbnail: ININThumbnail?
    public var description: String?
    public var waypoints: [ININWaypoint]?
    public var defaultOrientationY: Double?
    public var type: ININType?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["sceneGroup"] = self.sceneGroup?.encodeToJSON()
        nillableDictionary["assets"] = self.assets?.encodeToJSON()
        nillableDictionary["thumbnail"] = self.thumbnail?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["waypoints"] = self.waypoints?.encodeToJSON()
        nillableDictionary["defaultOrientationY"] = self.defaultOrientationY
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
