//
// ININOrganizationPresence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININOrganizationPresence: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var languageLabels: [String:String]?
    public var systemPresence: String?
    public var deactivated: Bool?
    public var primary: Bool?
    public var createdBy: ININUser?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var createdDate: NSDate?
    public var modifiedBy: ININUser?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var modifiedDate: NSDate?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["languageLabels"] = self.languageLabels?.encodeToJSON()
        nillableDictionary["systemPresence"] = self.systemPresence
        nillableDictionary["deactivated"] = self.deactivated
        nillableDictionary["primary"] = self.primary
        nillableDictionary["createdBy"] = self.createdBy?.encodeToJSON()
        nillableDictionary["createdDate"] = self.createdDate?.encodeToJSON()
        nillableDictionary["modifiedBy"] = self.modifiedBy?.encodeToJSON()
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
