//
// ININDomainPhysicalCapabilities.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININDomainPhysicalCapabilities: JSONEncodable {
    public var vlan: Bool?
    public var team: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["vlan"] = self.vlan
        nillableDictionary["team"] = self.team
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
