//
// ININTimeOffRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININTimeOffRequest: JSONEncodable {
    public enum ININStatus: String { 
        case Pending = "PENDING"
        case Approved = "APPROVED"
        case Denied = "DENIED"
        case Canceled = "CANCELED"
    }
    public var id: String?
    public var user: ININUser?
    public var isFullDayRequest: Bool?
    public var markedAsRead: Bool?
    public var activityCodeId: String?
    public var status: ININStatus?
    public var partialDayStartDateTimes: [NSDate]?
    public var fullDayManagementUnitDates: [String]?
    public var dailyDurationMinutes: Int32?
    public var notes: String?
    public var submittedBy: ININUser?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var submittedDate: NSDate?
    public var reviewedBy: ININUser?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var reviewedDate: NSDate?
    public var modifiedBy: ININUser?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var modifiedDate: NSDate?
    public var name: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["isFullDayRequest"] = self.isFullDayRequest
        nillableDictionary["markedAsRead"] = self.markedAsRead
        nillableDictionary["activityCodeId"] = self.activityCodeId
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["partialDayStartDateTimes"] = self.partialDayStartDateTimes?.encodeToJSON()
        nillableDictionary["fullDayManagementUnitDates"] = self.fullDayManagementUnitDates?.encodeToJSON()
        nillableDictionary["dailyDurationMinutes"] = self.dailyDurationMinutes?.encodeToJSON()
        nillableDictionary["notes"] = self.notes
        nillableDictionary["submittedBy"] = self.submittedBy?.encodeToJSON()
        nillableDictionary["submittedDate"] = self.submittedDate?.encodeToJSON()
        nillableDictionary["reviewedBy"] = self.reviewedBy?.encodeToJSON()
        nillableDictionary["reviewedDate"] = self.reviewedDate?.encodeToJSON()
        nillableDictionary["modifiedBy"] = self.modifiedBy?.encodeToJSON()
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
