//
// ININUtilization.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININUtilization: JSONEncodable {
    /** Map of media types to utilization settings.  Map keys can be: call, chat, email, or socialExpression */
    public var utilization: [String:ININOrgMediaUtilization]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["utilization"] = self.utilization?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
