//
// ININWorkItemCommandGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININWorkItemCommandGroup: JSONEncodable {
    public var category: String?
    public var defaultCommandId: String?
    public var commands: [ININWorkItemCommand]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["category"] = self.category
        nillableDictionary["defaultCommandId"] = self.defaultCommandId
        nillableDictionary["commands"] = self.commands?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
