//
// ININClientTextTableTransform.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININClientTextTableTransform: JSONEncodable {
    public var id: String?
    public var endpointId: String?
    public var filenameReplaces: [ININBasicTransform]?
    public var tags: [ININTagModel]?
    public var name: String?
    public var comments: String?
    public var delimiter: String?
    public var table: ININTableTransform?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["endpointId"] = self.endpointId
        nillableDictionary["filenameReplaces"] = self.filenameReplaces?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["comments"] = self.comments
        nillableDictionary["delimiter"] = self.delimiter
        nillableDictionary["table"] = self.table?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
