//
// ININGistener.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININGistener: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Creation date for the entity. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date the entity was last modified. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    /** Indicates if this Gistener may be utilized on another entity */
    public var enabled: Bool?
    /** A tweet must contain any one of these words */
    public var anyWords: String?
    /** A tweet must contain every one of these words in any order */
    public var allWords: String?
    /** If a tweet contains any one of these words, it is thrown out */
    public var excludeWords: String?
    /** A tweet must contain this exact quoted phrase */
    public var exactPhrase: String?
    /** The group tags associated with this Gistener */
    public var groupTags: [ININGroupTag]?
    /** The social account associated with this Gistener */
    public var socialAccount: ININSocialAccount?
    /** The operator queue the gistener will route to. */
    public var queue: ININQueue?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["anyWords"] = self.anyWords
        nillableDictionary["allWords"] = self.allWords
        nillableDictionary["excludeWords"] = self.excludeWords
        nillableDictionary["exactPhrase"] = self.exactPhrase
        nillableDictionary["groupTags"] = self.groupTags?.encodeToJSON()
        nillableDictionary["socialAccount"] = self.socialAccount?.encodeToJSON()
        nillableDictionary["queue"] = self.queue?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
