//
// ININCharge.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININCharge: JSONEncodable {
    public var licenseCount: Int32?
    public var name: String?
    public var description: String?
    public var price: Double?
    public var unitOfMeasure: String?
    public var billingPeriod: String?
    public var quantity: Int32?
    public var includedUnits: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["licenseCount"] = self.licenseCount?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["price"] = self.price
        nillableDictionary["unitOfMeasure"] = self.unitOfMeasure
        nillableDictionary["billingPeriod"] = self.billingPeriod
        nillableDictionary["quantity"] = self.quantity?.encodeToJSON()
        nillableDictionary["includedUnits"] = self.includedUnits?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
