//
// ININResponseFilter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used to filter response queries */
public class ININResponseFilter: JSONEncodable {
    public enum ININOperator: String { 
        case In = "IN"
        case Equals = "EQUALS"
        case Notequals = "NOTEQUALS"
    }
    /** Field to filter on. Allowed values are &#39;name&#39; and &#39;libraryId. */
    public var name: String?
    /** Filter operation: IN, EQUALS, NOTEQUALS. */
    public var _operator: ININOperator?
    /** Values to filter on. */
    public var values: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["operator"] = self._operator?.rawValue
        nillableDictionary["values"] = self.values?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
