//
// ININLocationEmergencyNumber.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININLocationEmergencyNumber: JSONEncodable {
    public enum ININType: String { 
        case Default = "default"
        case Elin = "elin"
    }
    public var e164: String?
    public var number: String?
    /** The type of emergency number. */
    public var type: ININType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["e164"] = self.e164
        nillableDictionary["number"] = self.number
        nillableDictionary["type"] = self.type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
