//
// ININWorkspace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININWorkspace: JSONEncodable {
    public enum ININType: String { 
        case User = "USER"
        case Group = "GROUP"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var type: ININType?
    public var isCurrentUserWorkspace: Bool?
    public var user: ININUriReference?
    public var bucket: String?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    public var summary: ININWorkspaceSummary?
    public var acl: [String]?
    public var description: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["isCurrentUserWorkspace"] = self.isCurrentUserWorkspace
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["bucket"] = self.bucket
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["summary"] = self.summary?.encodeToJSON()
        nillableDictionary["acl"] = self.acl?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
