//
// ININArchiveRetention.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININArchiveRetention: JSONEncodable {
    public enum ININStorageMedium: String { 
        case Cloudarchive = "CLOUDARCHIVE"
    }
    public var days: Int32?
    public var storageMedium: ININStorageMedium?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["days"] = self.days?.encodeToJSON()
        nillableDictionary["storageMedium"] = self.storageMedium?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
