//
// ININWorkspaceMember.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININWorkspaceMember: JSONEncodable {
    public enum ININMemberType: String { 
        case User = "USER"
        case Group = "GROUP"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    public var workspace: ININUriReference?
    public var memberType: ININMemberType?
    public var member: ININUriReference?
    public var user: ININUser?
    public var group: ININGroup?
    public var securityProfile: ININSecurityProfile?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["workspace"] = self.workspace?.encodeToJSON()
        nillableDictionary["memberType"] = self.memberType?.rawValue
        nillableDictionary["member"] = self.member?.encodeToJSON()
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["group"] = self.group?.encodeToJSON()
        nillableDictionary["securityProfile"] = self.securityProfile?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
