//
// ININResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about a response. */
public class ININResponse: JSONEncodable {
    public enum ININInteractionType: String { 
        case Chat = "chat"
        case Email = "email"
        case Twitter = "twitter"
    }
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Version number required for updates. */
    public var version: Int32?
    /** One or more libraries response is associated with. */
    public var libraries: [ININUriReference]?
    /** One or more texts associated with the response. */
    public var texts: [ININResponseText]?
    /** User that created the response */
    public var createdBy: ININUser?
    /** The date and time the response was created. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** The interaction type for this response. */
    public var interactionType: ININInteractionType?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["version"] = self.version?.encodeToJSON()
        nillableDictionary["libraries"] = self.libraries?.encodeToJSON()
        nillableDictionary["texts"] = self.texts?.encodeToJSON()
        nillableDictionary["createdBy"] = self.createdBy?.encodeToJSON()
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["interactionType"] = self.interactionType?.rawValue
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
