//
// ININExpressionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININExpressionResponse: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** Creation date for the entity. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateCreated: NSDate?
    /** Date the entity was last modified. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var dateModified: NSDate?
    /** The name of the social hub. */
    public var socialHub: String?
    /** The conversation that this response is a part of. */
    public var conversation: ININConversation?
    /** The twitter expression that this is in response to. */
    public var twitterExpression: ININTwitterExpression?
    /** The raw text of the response. */
    public var rawResponseText: String?
    /** The Social Account used to publish this expression */
    public var socialAccount: ININSocialAccount?
    /** The id given to this response from the social hub */
    public var socialHubResponseId: String?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["dateCreated"] = self.dateCreated?.encodeToJSON()
        nillableDictionary["dateModified"] = self.dateModified?.encodeToJSON()
        nillableDictionary["socialHub"] = self.socialHub
        nillableDictionary["conversation"] = self.conversation?.encodeToJSON()
        nillableDictionary["twitterExpression"] = self.twitterExpression?.encodeToJSON()
        nillableDictionary["rawResponseText"] = self.rawResponseText
        nillableDictionary["socialAccount"] = self.socialAccount?.encodeToJSON()
        nillableDictionary["socialHubResponseId"] = self.socialHubResponseId
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
