//
// ININVoiceRateUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ININVoiceRateUpdate: JSONEncodable {
    /** The globally unique identifier for the object. */
    public var id: String?
    public var name: String?
    /** The ISO 4217 currency code of the voice rate. */
    public var currency: String?
    /** The inbound toll free rate. */
    public var inboundTollFree: ININVoiceRate?
    /** The domestic extended rates. */
    public var extended: [ININVoiceRateExtended]?
    /** The inbound tolled rate. */
    public var inboundTolled: ININVoiceRate?
    /** The outbound local rate. */
    public var outboundLocal: ININVoiceRate?
    /** The outbound intra-state rate. */
    public var outboundIntraState: ININVoiceRate?
    /** The outbound inter-state rate. */
    public var outboundInterState: ININVoiceRate?
    /** The outbound international rates. */
    public var outboundInternational: [ININVoiceRateInternational]?
    /** The date of the rate amendment. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var amendmentDate: NSDate?
    /** The effective date of the rate amendment. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ */
    public var effectiveDate: NSDate?
    /** The URI for this object */
    public var selfUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["currency"] = self.currency
        nillableDictionary["inboundTollFree"] = self.inboundTollFree?.encodeToJSON()
        nillableDictionary["extended"] = self.extended?.encodeToJSON()
        nillableDictionary["inboundTolled"] = self.inboundTolled?.encodeToJSON()
        nillableDictionary["outboundLocal"] = self.outboundLocal?.encodeToJSON()
        nillableDictionary["outboundIntraState"] = self.outboundIntraState?.encodeToJSON()
        nillableDictionary["outboundInterState"] = self.outboundInterState?.encodeToJSON()
        nillableDictionary["outboundInternational"] = self.outboundInternational?.encodeToJSON()
        nillableDictionary["amendmentDate"] = self.amendmentDate?.encodeToJSON()
        nillableDictionary["effectiveDate"] = self.effectiveDate?.encodeToJSON()
        nillableDictionary["selfUri"] = self.selfUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
