//
// FaxAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class FaxAPI: APIBase {
    /**
     Delete a fax document.
     
     - parameter documentId: (path) Document ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteFaxDocumentsDocumentId(documentId documentId: String, completion: ((error: ErrorType?) -> Void)) {
        deleteFaxDocumentsDocumentIdWithRequestBuilder(documentId: documentId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a fax document.
     - DELETE /api/v2/fax/documents/{documentId}
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     
     - parameter documentId: (path) Document ID 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteFaxDocumentsDocumentIdWithRequestBuilder(documentId documentId: String) -> RequestBuilder<Void> {
        var path = "/api/v2/fax/documents/{documentId}"
        path = path.stringByReplacingOccurrencesOfString("{documentId}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get a list of fax documents.
     
     - parameter pageSize: (query) Page size (optional, default to 25)
     - parameter pageNumber: (query) Page number (optional, default to 1)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getFaxDocuments(pageSize pageSize: Int32? = nil, pageNumber: Int32? = nil, completion: ((data: ININFaxDocumentEntityListing?, error: ErrorType?) -> Void)) {
        getFaxDocumentsWithRequestBuilder(pageSize: pageSize, pageNumber: pageNumber).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a list of fax documents.
     - GET /api/v2/fax/documents
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example={
  "total" : 123456789,
  "pageCount" : 123,
  "pageNumber" : 123,
  "entities" : [ {
    "callerAddress" : "aeiou",
    "workspace" : {
      "selfUri" : "aeiou",
      "name" : "aeiou",
      "id" : "aeiou"
    },
    "pageCount" : 123456789,
    "read" : true,
    "downloadSharingUri" : "aeiou",
    "selfUri" : "aeiou",
    "dateModified" : "2000-01-23T04:56:07.000+0000",
    "receiverAddress" : "aeiou",
    "dateCreated" : "2000-01-23T04:56:07.000+0000",
    "filename" : "aeiou",
    "createdBy" : "",
    "contentUri" : "aeiou",
    "name" : "aeiou",
    "contentLength" : 123456789,
    "id" : "aeiou",
    "thumbnails" : [ {
      "imageUri" : "aeiou",
      "resolution" : "aeiou"
    } ],
    "contentType" : "aeiou",
    "sharingUri" : "aeiou"
  } ],
  "firstUri" : "aeiou",
  "selfUri" : "aeiou",
  "lastUri" : "aeiou",
  "pageSize" : 123,
  "previousUri" : "aeiou",
  "nextUri" : "aeiou"
}}]
     
     - parameter pageSize: (query) Page size (optional, default to 25)
     - parameter pageNumber: (query) Page number (optional, default to 1)

     - returns: RequestBuilder<ININFaxDocumentEntityListing> 
     */
    public class func getFaxDocumentsWithRequestBuilder(pageSize pageSize: Int32? = nil, pageNumber: Int32? = nil) -> RequestBuilder<ININFaxDocumentEntityListing> {
        let path = "/api/v2/fax/documents"
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "pageSize": pageSize?.encodeToJSON(),
            "pageNumber": pageNumber?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ININFaxDocumentEntityListing>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get a document.
     
     - parameter documentId: (path) Document ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getFaxDocumentsDocumentId(documentId documentId: String, completion: ((data: ININFaxDocument?, error: ErrorType?) -> Void)) {
        getFaxDocumentsDocumentIdWithRequestBuilder(documentId: documentId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a document.
     - GET /api/v2/fax/documents/{documentId}
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example={
  "callerAddress" : "aeiou",
  "workspace" : {
    "selfUri" : "aeiou",
    "name" : "aeiou",
    "id" : "aeiou"
  },
  "pageCount" : 123456789,
  "read" : true,
  "downloadSharingUri" : "aeiou",
  "selfUri" : "aeiou",
  "dateModified" : "2000-01-23T04:56:07.000+0000",
  "receiverAddress" : "aeiou",
  "dateCreated" : "2000-01-23T04:56:07.000+0000",
  "filename" : "aeiou",
  "createdBy" : "",
  "contentUri" : "aeiou",
  "name" : "aeiou",
  "contentLength" : 123456789,
  "id" : "aeiou",
  "thumbnails" : [ {
    "imageUri" : "aeiou",
    "resolution" : "aeiou"
  } ],
  "contentType" : "aeiou",
  "sharingUri" : "aeiou"
}}]
     
     - parameter documentId: (path) Document ID 

     - returns: RequestBuilder<ININFaxDocument> 
     */
    public class func getFaxDocumentsDocumentIdWithRequestBuilder(documentId documentId: String) -> RequestBuilder<ININFaxDocument> {
        var path = "/api/v2/fax/documents/{documentId}"
        path = path.stringByReplacingOccurrencesOfString("{documentId}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ININFaxDocument>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Download a fax document.
     
     - parameter documentId: (path) Document ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getFaxDocumentsDocumentIdContent(documentId documentId: String, completion: ((data: ININDownloadResponse?, error: ErrorType?) -> Void)) {
        getFaxDocumentsDocumentIdContentWithRequestBuilder(documentId: documentId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Download a fax document.
     - GET /api/v2/fax/documents/{documentId}/content
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example={
  "contentLocationUri" : "aeiou",
  "imageUri" : "aeiou"
}}]
     
     - parameter documentId: (path) Document ID 

     - returns: RequestBuilder<ININDownloadResponse> 
     */
    public class func getFaxDocumentsDocumentIdContentWithRequestBuilder(documentId documentId: String) -> RequestBuilder<ININDownloadResponse> {
        var path = "/api/v2/fax/documents/{documentId}/content"
        path = path.stringByReplacingOccurrencesOfString("{documentId}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ININDownloadResponse>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get fax summary
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getFaxSummary(completion: ((data: ININFaxSummary?, error: ErrorType?) -> Void)) {
        getFaxSummaryWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get fax summary
     - GET /api/v2/fax/summary
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example={
  "unreadCount" : 123,
  "readCount" : 123,
  "totalCount" : 123
}}]

     - returns: RequestBuilder<ININFaxSummary> 
     */
    public class func getFaxSummaryWithRequestBuilder() -> RequestBuilder<ININFaxSummary> {
        let path = "/api/v2/fax/summary"
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ININFaxSummary>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Update a fax document.
     
     - parameter documentId: (path) Document ID 
     - parameter body: (body) Document (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func putFaxDocumentsDocumentId(documentId documentId: String, body: ININFaxDocument? = nil, completion: ((data: ININFaxDocument?, error: ErrorType?) -> Void)) {
        putFaxDocumentsDocumentIdWithRequestBuilder(documentId: documentId, body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Update a fax document.
     - PUT /api/v2/fax/documents/{documentId}
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example={
  "callerAddress" : "aeiou",
  "workspace" : {
    "selfUri" : "aeiou",
    "name" : "aeiou",
    "id" : "aeiou"
  },
  "pageCount" : 123456789,
  "read" : true,
  "downloadSharingUri" : "aeiou",
  "selfUri" : "aeiou",
  "dateModified" : "2000-01-23T04:56:07.000+0000",
  "receiverAddress" : "aeiou",
  "dateCreated" : "2000-01-23T04:56:07.000+0000",
  "filename" : "aeiou",
  "createdBy" : "",
  "contentUri" : "aeiou",
  "name" : "aeiou",
  "contentLength" : 123456789,
  "id" : "aeiou",
  "thumbnails" : [ {
    "imageUri" : "aeiou",
    "resolution" : "aeiou"
  } ],
  "contentType" : "aeiou",
  "sharingUri" : "aeiou"
}}]
     
     - parameter documentId: (path) Document ID 
     - parameter body: (body) Document (optional)

     - returns: RequestBuilder<ININFaxDocument> 
     */
    public class func putFaxDocumentsDocumentIdWithRequestBuilder(documentId documentId: String, body: ININFaxDocument? = nil) -> RequestBuilder<ININFaxDocument> {
        var path = "/api/v2/fax/documents/{documentId}"
        path = path.stringByReplacingOccurrencesOfString("{documentId}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = PureCloudApiClientAPI.basePath + path
        let parameters = body?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ININFaxDocument>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
