//
// TokensAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class TokensAPI: APIBase {
    /**
     Delete  auth token used to make the request.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteTokensMe(completion: ((data: String?, error: ErrorType?) -> Void)) {
        deleteTokensMeWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Delete  auth token used to make the request.
     - DELETE /api/v2/tokens/me
     - 
     - OAuth:
       - type: oauth2
       - name: PureCloud Auth
     - examples: [{contentType=application/json, example="aeiou"}]

     - returns: RequestBuilder<String> 
     */
    public class func deleteTokensMeWithRequestBuilder() -> RequestBuilder<String> {
        let path = "/api/v2/tokens/me"
        let URLString = PureCloudApiClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = PureCloudApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
